name: Update README Widget Themes

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Update README.md with new themes
        run: |
          # Define random themes for each widget
          stats_themes=("dark" "radical" "merko" "tokyonight")
          streak_themes=("dark" "radical" "merko" "tokyonight")
          langs_themes=("dark" "radical" "merko" "tokyonight")

          # Select random themes
          stats_theme=${stats_themes[$((RANDOM % ${#stats_themes[@]}))]}
          streak_theme=${streak_themes[$((RANDOM % ${#streak_themes[@]}))]}
          langs_theme=${langs_themes[$((RANDOM % ${#langs_themes[@]}))]}

          echo "Selected stats theme: $stats_theme"
          echo "Selected streak theme: $streak_theme"
          echo "Selected top languages theme: $langs_theme"

          # Update GitHub Stats widget
          sed -i "s|\(https://github-readme-stats\.vercel\.app/api?username=armaaan&[^\"]*theme=\)[^&\"]*|\1$stats_theme|" README.md

          # Update GitHub Streak widget
          sed -i "s|\(https://github-readme-streak-stats\.herokuapp\.com/\?user=armaaan&[^\"]*theme=\)[^&\"]*|\1$streak_theme|" README.md

          # Update Top Languages widget
          sed -i "s|\(https://github-readme-stats\.vercel\.app/api/top-langs/\?username=armaaan&[^\"]*theme=\)[^&\"]*|\1$langs_theme|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update themes: Stats=$stats_theme, Streak=$streak_theme, Languages=$langs_theme"
          git push
